spring.datasource.url=jdbc:postgresql://72.56.106.83:5432/db_cinemate
spring.datasource.username=kostya
spring.datasource.password=Pro100tip
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.ssl-mode=disable

server.forward-headers-strategy=native
spring.task.scheduling.pool.size=2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
jwt.secret=786fd2396b808634d9ce7883bae350e396deb83ca0536d9c6740a8d6

server.port=8080
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.image.base-url=https://image.tmdb.org/t/p

tmdb.api.key=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlYjUyOTVlODQ0YTMzYjM1NDQ5MzE0OGU4NGM5OGQ4MSIsIm5iZiI6MTc1ODExMjg0NC45NTIsInN1YiI6IjY4Y2FhYzRjZWE0ZWFhOTU4MWM3ZjU5NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.k1xlXY-WCGTKWZwBdlm01lfzlmwdItZ6sABbIuLHrmk

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.display-request-duration=true

springdoc.api-docs.resolve-schema-properties=false
springdoc.override-with-generic-response=false

timeweb.s3.access-key=I1VIPFWDKIHNQO6K211J
timeweb.s3.secret-key=cRnYnOGwrhsAopCt1aJcEyHC2NEsnIbGq0WVja1t
timeweb.s3.endpoint=https://s3.twcstorage.ru
timeweb.s3.region=ru-1
timeweb.s3.bucket-name=714ed503-f3d2-440d-9b7d-35532a7ca263

timeweb.s3.public-url=https://s3.twcstorage.ru/714ed503-f3d2-440d-9b7d-35532a7ca263