spring.datasource.url=jdbc:postgresql://ep-falling-cloud-adoj6poj-pooler.c-2.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_F3mvk8UfGYqA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.ssl-mode=require

spring.task.scheduling.pool.size=2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
jwt.secret=786fd2396b808634d9ce7883bae350e396deb83ca0536d9c6740a8d6

tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.image.base-url=https://image.tmdb.org/t/p

tmdb.api.key=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlYjUyOTVlODQ0YTMzYjM1NDQ5MzE0OGU4NGM5OGQ4MSIsIm5iZiI6MTc1ODExMjg0NC45NTIsInN1YiI6IjY4Y2FhYzRjZWE0ZWFhOTU4MWM3ZjU5NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.k1xlXY-WCGTKWZwBdlm01lfzlmwdItZ6sABbIuLHrmk